### PR TITLE
Caching scheme changed with respect to ember-cli-htmlbars

### PR DESCRIPTION
**Pull request by Darshan-Chauhan**
This PR fixes [#109](https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/issues/109)

To keep `ember-cli-htmlbars` caching in sync, `astPlugins()` function needs to be same as in `ember-cli-htmlbars`
 [astPlugins() => https://github.com/ember-cli/ember-cli-htmlbars/blob/master/ember-addon-main.js#L103-#L135](https://github.com/ember-cli/ember-cli-htmlbars/blob/master/ember-addon-main.js#L103-#L135)

### CODE REVIEW

**Comment by Darshan-Chauhan** [comment]
@rwjblue , done.

**Comment by rwjblue** [comment]
Can you rebase?

**Comment by Darshan-Chauhan** [comment]
@rwjblue , Done.

**Comment by Darshan-Chauhan** [comment]
Ping @Turbo87 , can we merge this?

**Comment by Turbo87** [comment]
is it not possible to use the code from `ember-cli-htmlbars` directly?

**Comment by rwjblue** [comment]
Sorry for the run around here, I'm going to go ahead and close this in favor of the changes proposed in #320 (and implemented in ember-cli-htmlbars@4.0.0+).

**Pull request closed without merging**
